### ISSUE TITLE
How can I connect two pos printers to an android device?

### ISSUE THREAD

**Issue by AlexZhouAA** [ebc81/Esc_pos_android#1]
When I use one pos printer it works perfectly.

When I connect two pos printers using usb hub to android devices, only one printer works. Another one  complains like the following,

<pre>
 Attempt to invoke  virtual method 'int android.hardware.usb.UsbInterface.getId()' on a null object reference
</pre>

I even tried to call USBPort.SetUSBConnectionFlag(false) and  USBPort.connect_device(foundDevice) before I called AddData2Printer, I still got the same issue.

**Comment by ebc81** [comment]
yes this is not supported:
USBPort.java would need some changes
instread of holding just one device
`private`  UsbDevice   `mUsbConnectedDevice;`
should be a list or array.
Function
`public Boolean connect_device(UsbDevice usbDev)`
needs than also modifyied ...
