### ISSUE TITLE
How to print some special char

### ISSUE THREAD

**Issue by gauthier-marchand** [ebc81/Esc_pos_android#2]
Hi, 

I tried to print some char like é or è but it didn't work.. 

I tried to change the encode from ISO-8859-1 to UTF-8 but it's not working.

Do you have an idea how can I do that ? 

Thank in advance, 

Best regards,

**Comment by ebc81** [comment]
In the ESC_POS_EPSON_ANDROID.java there is an example with german UMLAUTE ÄÖÜß
have a look at the print_sample1()
Code page is WPC1252

**Comment by gauthier-marchand** [comment]
Hi,
Thank you, I tried with WCP1252 but the sign € does not be printed..

BR,

Cordialement,

_Gauthier MARCHAND_

_06 98 85 50 28_
_Développeur chez BCOME *
*http://bcome.fr/_ http://bcome.fr/

2016-05-29 11:04 GMT+02:00 ebc81 notifications@github.com:

**Comment by gauthier-marchand** [comment]
Hi,

There is another thing that I don't understand..

About the barcode, CODE93 and CODE128 were commented.. Do they work ?

I tried to use them but.. the printer does not recognize the barcode..

Do you have any answer ? :)

BR,

Cordialement,

_Gauthier MARCHAND_

_06 98 85 50 28_
_Développeur chez BCOME *
*http://bcome.fr/_ http://bcome.fr/

2016-05-30 17:00 GMT+02:00 Gauthier Marchand gauthier.mcd@gmail.com:

**Comment by gauthier-marchand** [comment]
Ok problem solved via the epson doc.

I created a method to print barcode with barcode type between 65 and 73.

I could give you this one to put it in your lib if you want.

BR,

Cordialement,

_Gauthier MARCHAND_

_06 98 85 50 28_
_Développeur chez BCOME *
*http://bcome.fr/_ http://bcome.fr/

2016-05-31 9:53 GMT+02:00 Gauthier Marchand gauthier.mcd@gmail.com:

**Comment by ebc81** [comment]
Hi ,
I think you can add you methode via pull request. ( I am not so famillar with git hub ). Otherwise you can send it to me, info@ebcTech.eu
Currently I have not so much time, and the project I was using this lib is finished since a long time.
I only have tested barcode 39 and EAN13. For EAN13 for example I found out that if you don't use a valid EAN13 code , my EPSON receipt printer just do not print out the barcode.
